import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SliderProvider } from "./context/sliderContext";
import { CertificationsProvider } from "./context/CertificationsContext";
import { PartnersProvider } from "./context/PartnersContext";
import { ProjectsProvider } from "./context/projectContext";
import { ClientProvider } from "./context/clientContext";
import { EgyClientProvider } from "./context/egyClientContext";
import { ProductsProvider } from "./context/ProductContext";
import { AboutUsProvider } from "./context/aboutUsContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Powercem",
  description: "Generated by Abdallah wael",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SliderProvider>
        <CertificationsProvider>
        <PartnersProvider>
          <ProjectsProvider>
            <ClientProvider>
              <EgyClientProvider>
                <ProductsProvider> 
                  <AboutUsProvider>
            {children}
                 </AboutUsProvider>
                </ProductsProvider>
            </EgyClientProvider>
            </ClientProvider>
            </ProjectsProvider>
        </PartnersProvider>
          </CertificationsProvider>
        </SliderProvider>
      </body>
    </html>
  );
}
